baseurl = "https://www.fccmontevideo.com/"
languageCode = "es-uy"
title = "FCC Montevideo"
googleAnalytics = "UA-69160067-3"


[params]
description = "Comunidad Free Code Camp Montevideo"
disqusShortname = "free-code-camp-montevideo"
facebookGroup = "https://www.facebook.com/groups/free.code.camp.montevideo"
twitter = "https://twitter.com/fccmontevideo"
githubOrg = "https://github.com/FreeCodeCampMontevideo"
youtube = "https://www.youtube.com/channel/UCTIYpVhXmFgTZ9CiuAU22Rw"

[[menu.main]]
  name = "Blog"
  weight = -100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Eventos"
  weight = -110
  identifier = "events"
  url = "/events/"
